services:
  - type: web
    name: geelong-garage
    env: node
    buildCommand: |
      echo "VITE_CONVEX_URL=$VITE_CONVEX_URL" > .env
      echo "VITE_CLERK_PUBLISHABLE_KEY=$VITE_CLERK_PUBLISHABLE_KEY" >> .env
      echo "VITE_GIPHY_API_KEY=$VITE_GIPHY_API_KEY" >> .env
      npm run render-build
    startCommand: npm start
    envVars:
      - key: VITE_CONVEX_URL
        value: https://patient-tern-95.convex.cloud
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: CONVEX_DEPLOY_KEY
        sync: false
      - key: VITE_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: VITE_GIPHY_API_KEY
        value: FCkpvv7ExFjZrN6fjv013nFsnGXBXcVv
    autoDeploy: true
    plan: starter

  - type: web
    name: geelong-garage-pdf-service
    env: image
    image:
      url: ghcr.io/puppeteer/puppeteer:21.5.2
    plan: starter
    startCommand: bash -c "curl -s https://raw.githubusercontent.com/stevejford/geelonggarage/master/pdf-service/start.sh | bash"
    envVars:
      - key: PORT
        value: 3001
      - key: API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://patient-tern-95.convex.site,https://grandiose-swordfish-144.convex.site,http://localhost:5173,http://localhost:3000
      - key: RENDER
        value: true
    disk:
      name: pdf-service-data
      mountPath: /app
      sizeGB: 1
