services:
  - type: web
    name: geelong-garage-pdf-service
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3001
      - key: API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://patient-tern-95.convex.site,https://grandiose-swordfish-144.convex.site,http://localhost:5173
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
